ConnectIn-master/ConnectInSolution/ConnectIn/Models/Entity/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ConnectIn.Models.Entity
{
    public class Comment
    {
        #region Columns
        [Key]
        public int CommentId { get; set; }
        public string UserId { get; set; }
        public int PostId { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        #endregion

        #region ForeignKeys
        public User User { get; set; }
        public Post Post { get; set; }
        #endregion

        public Comment()
        {
            Date = DateTime.Now;
        }
    }
}

ConnectIn-master/ConnectInSolution/ConnectIn/Models/ViewModels/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ConnectIn.Models.Entity;

namespace ConnectIn.Models.ViewModels
{
    public class CommentViewModel
    {
        public int CommentId { get; set; }
        public int PostId { get; set; }
        public UserViewModel User { get; set; }
        public string Body { get; set; }
        public DateTime DateInserted { get; set; }
        public bool IsUserCommentOwner { get; set; }

    }
}

ConnectIn-master/ConnectInSolution/ConnectIn/Controllers/StatusController.cs
using System;
using System.Web.Mvc;
using System.Web.WebPages;
using ConnectIn.DAL;
using ConnectIn.Models.Entity;
using ConnectIn.Services;
using Microsoft.AspNet.Identity;
using Microsoft.Ajax.Utilities;
using ConnectIn.Models.ViewModels;
using System.Collections.Generic;
using Microsoft.Ajax.Utilities;

namespace ConnectIn.Controllers
{
    public class StatusController : Controller
    {
        private readonly ApplicationDbContext DbContext = new ApplicationDbContext();

        [HttpPost, Authorize]
        public ActionResult AddPost(FormCollection collection)
        {
            string amount = collection["amount"];
            string status = collection["status"];
            string groupId = collection["idOfGroup"];
            if(status.IsNullOrWhiteSpace() || amount.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            // Create the new post and add it into the database
            DateTime now = DateTime.Now;
            var newPost = new Post
            {
                UserId = User.Identity.GetUserId(),
                Date = now,
                Text = status
            };

            if (!groupId.IsNullOrWhiteSpace())
            {
                newPost.GroupId = Int32.Parse(groupId);
            }

            DbContext.Posts.Add(newPost);
            DbContext.SaveChanges();

            // Find out if this post belongs to the newsfeed or a group
            var groupService = new GroupService(DbContext);
            var userService = new UserService(DbContext);
            var list = new List<int>();
            if (groupId.IsNullOrWhiteSpace())
            {
                list = userService.GetEveryNewsFeedPostsForUser(User.Identity.GetUserId());
            }
            else
            {
                list = groupService.GetAllPostsOfGroup(Int32.Parse(groupId));
            }

            var postService = new PostService(DbContext);
            var likeDislikeService = new LikeDislikeService(DbContext);
            var postList = new List<PostsViewModel>();
            int nOfCurrentStatuses = Int32.Parse(amount);

            // Get all statuses that are not currently displayed and display them
            for (int i = (list.Count - nOfCurrentStatuses) - 1; i >= 0 ; i--)
            {
                var post = postService.GetPostById(list[i]);

                // Assign a smiley according to if this user has liked or dislike or not done either
                var likeDislike = likeDislikeService.GetLikeDislike(post.UserId, post.PostId);
                string lPic = null, dPic = null;
                if (likeDislike == null)
                {
                    lPic = "/Content/images/smileySMALL.png";
                    dPic = "/Content/images/sadfaceSMALL.png";
                }
                else if (likeDislike.Like)
                {
                    lPic = "/Content/images/smileyGREEN.png";
                    dPic = "/Content/images/sadfaceSMALL.png";
                }
                else if (likeDislike.Dislike)
                {
                    lPic = "/Content/images/smileySMALL.png";
                    dPic = "/Content/images/sadfaceRED.png";
                }

                // Fill in the viewmodel
                postList.Add(
                    new PostsViewModel()
                    {
                        PostId = post.PostId,
                        Body = post.Text,
                        User = new UserViewModel()
                        {
                            UserId = post.UserId,
                            Name = userService.GetUserById(post.UserId).Name,
                            ProfilePicture = userService.GetProfilePicture(post.UserId).PhotoPath
                        },
                        DateInserted = post.Date,
                        LikeDislikeComment = new LikeDislikeCommentViewModel()
                        {
                            Likes = postService.GetPostsLikes(post.PostId),
                            Dislikes = postService.GetPostsDislikes(post.PostId),
                            Comments = postService.GetPostsComments(post.PostId).Count
                        },
                        LikePic = lPic,
                        DislikePic = dPic,
                        isUserPostOwner = (post.UserId == User.Identity.GetUserId()) 
                    });
            }

            return Json(postList, JsonRequestBehavior.AllowGet);        
        }


        [HttpPost, Authorize]
        public ActionResult RemovePost(FormCollection collection)
        {
            string id = collection["postId"];
            if (id.IsNullOrWhiteSpace())
            {
                return View("Error");
            }
            int postId = Int32.Parse(id);


            // Remove the post
            var postService = new PostService(DbContext);
            var post = postService.GetPostById(postId);
            if (post != null)
            {
                DbContext.Posts.Remove(post);
                DbContext.SaveChanges();
            }
            
            // If we are deleting from the comment view the action is redirected to newsfeed
            var url = ControllerContext.HttpContext.Request.UrlReferrer;
            if (url != null && url.AbsolutePath.Contains("Comment"))
            {
                return RedirectToAction("NewsFeed", "Home");
            }

            // If we are in the newsfeed we delete and return nothing to the ajax call
            return new EmptyResult();
        }

        [HttpGet, Authorize]
        public ActionResult Comment(int? postId)
        {
            if (!postId.HasValue)
            {
                return RedirectToAction("NewsFeed", "Home");
            }

            // Assign a smiley according to if this user has liked or dislike or not done either
            var likedislikeService = new LikeDislikeService(DbContext);
            int pid = postId.Value;
            string lPic = null, dPic = null;
            if (likedislikeService.GetLikeDislike(User.Identity.GetUserId(), pid) == null)
            {
                lPic = "~/Content/images/smileySMALL.png";
                dPic = "~/Content/images/sadfaceSMALL.png";
            }
            else if (likedislikeService.GetLikeDislike(User.Identity.GetUserId(), pid).Like)
            {
                lPic = "~/Content/images/smileyGREEN.png";
                dPic = "~/Content/images/sadfaceSMALL.png";
            }
            else if (likedislikeService.GetLikeDislike(User.Identity.GetUserId(), pid).Dislike)
            {
                lPic = "~/Content/images/smileySMALL.png";
                dPic = "~/Content/images/sadfaceRED.png";
            }

            // Fill in the viewmodel
            var userService = new UserService(DbContext);
            var postService = new PostService(DbContext);
            var model = new CommentHelperViewModel
            {
                User = new UserViewModel()
                {
                    UserId = postService.GetPostById(pid).UserId,
                    Name = userService.GetUserById(postService.GetPostById(pid).UserId).Name,
                    ProfilePicture = userService.GetProfilePicture(User.Identity.GetUserId()).PhotoPath

                },
                Comments = new List<CommentViewModel>(),
                Post = new PostsViewModel()
                {
                    PostId = pid,
                    Body = postService.GetPostById(pid).Text,
                    DateInserted = postService.GetPostById(pid).Date,
                    LikeDislikeComment = new LikeDislikeCommentViewModel()
                    {
                        Likes = postService.GetPostsLikes(pid),
                        Dislikes = postService.GetPostsDislikes(pid),
                        Comments = postService.GetPostsCommentsCount(pid)
                    },
                    User = new UserViewModel()
                    {
                        UserId = postService.GetPostById(pid).UserId,
                        Name = userService.GetUserById(postService.GetPostById(pid).UserId).Name,
                        ProfilePicture = userService.GetProfilePicture(postService.GetPostById(pid).UserId).PhotoPath
                    },
                    LikePic = lPic,
                    DislikePic = dPic
                }
            };

            var commentService = new CommentService(DbContext);
            var commentIdList = postService.GetPostsComments(pid);
            foreach (var id in commentIdList)
            {
                var commentList = commentService.GetCommentById(id);
                model.Comments.Add(
                    new CommentViewModel()
                    {
                        CommentId = commentList.CommentId,
                        PostId = commentList.PostId,
                        Body = commentList.Text,
                        DateInserted = commentList.Date,
                        User = new UserViewModel()
                        {
                            UserId = commentList.UserId,
                            Name = userService.GetUserById(commentList.UserId).Name,
                            UserName = userService.GetUserById(commentList.UserId).UserName,
                            ProfilePicture = userService.GetProfilePicture(commentList.UserId).PhotoPath
                        }
                    });
            }

            return View(model);
        }

        [HttpPost, Authorize]
        public ActionResult AddComment(FormCollection collection)
        {
            string status = collection["status"];
            string postId = collection["postId"];
            string amount = collection["amount"];
            if (status.IsNullOrWhiteSpace() || postId.IsNullOrWhiteSpace() || amount.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

ConnectIn-master/ConnectInSolution/ConnectIn/Views/Status/Comment.cshtml
@using Microsoft.AspNet.Identity
@model ConnectIn.Models.ViewModels.CommentHelperViewModel
@{
    ViewBag.Title = "Comment";
}
@if (Request.IsAuthenticated)
{
    <h2>Comments
        <span style="float: right;">
            <button type="button" class="btn btn-warning" onclick="location.href = document.referrer;">Go back</button>
        </span>
    </h2>

    
    
    <div class="container">
        <div id="posts" class="row">
            <div class="post item span3">
                    <div class="well" id="FriendsListWell">
                        <div id="CommentPostWell">
                            <!--Should display user's profile picture, a cat was used temporarily-->
                            <div class="PostPartialViewPhoto">
                                <a href="/Home/Profile/@Model.Post.User.UserId"><img class="PartialViewResponsive img-rounded" src="@Url.Content(Model.Post.User.ProfilePicture)" alt="Profile Picture" /></a>
                            </div>
                            <!--Should display username instead of item.userID-->
                            <div class="friendsListName">
                                <h3 class="friendsListName">
                                    @Html.ActionLink(Model.Post.User.Name, "Profile", "Home", new {id = Model.Post.User.UserId}, null) <small class="pull-right">@Html.DisplayFor(modelItem => Model.Post.DateInserted)</small>
                                </h3>
                            </div>
                            <pre class="preReset">@Model.Post.Body</pre>
                        </div>

                        <div id="commentsLikesDeleteDiv">
                            <div id="commentsAndLikes">
                                <div id="reactionButtons">
                                    <input type="hidden" name="postId" value="@Model.Post.PostId" />
                                    <button type="submit" id="likeBtn-@Model.Post.PostId" class="btnNew btn-default-clicked likeBtn"><img id="likedislikeimg" src="@Url.Content(Model.Post.LikePic)" alt="Dislike Picture" />@Model.Post.LikeDislikeComment.Likes Smiles</button>
                                    <button type="submit" id="dislikeBtn-@Model.Post.PostId" class="btnNew btn-default-clicked dislikeBtn"><img id="likedislikeimg" src="@Url.Content(Model.Post.DislikePic)" alt="Dislike Picture" />@Model.Post.LikeDislikeComment.Dislikes Sadfaces</button>

                                    @if (Model.Post.User.UserId == User.Identity.GetUserId())
                                    {
                                        using (Html.BeginForm("RemovePost", "Status", new { postId = Model.Post.PostId }))
                                        {
                                            <input type="hidden" name="postId" value="@Model.Post.PostId" />
                                            <button type="submit" class="btn btn-danger deletePostButton">Delete Post</button>
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
    <div>
        <div class="NewsFeedContainer" >
            <div class="form-horizontal" style="margin-top: 10px; margin-bottom: 20px;">
                <input type="hidden" name="postId" value="@Model.Post.PostId" />
                <div class="PostPartialViewPhoto">
                    <a href="/Home/Profile/@User.Identity.GetUserId()"><img class="PartialViewResponsive img-rounded" src="@Url.Content(Model.User.ProfilePicture)" alt="Profile Picture" /></a>
                </div>
                <textarea placeholder="Comment..." class="commentform-control" rows="5" id="commentstatus" name="status"></textarea>
                <button type="button" id="submitcomment" class="btn btn-primary">Submit</button>
            </div>
            <hr />
        </div>



        </div>
    
    <div class="container">
        <div id="allcomments" class="row  ">
            @foreach (var item in Model.Comments)
            {
                <div id="comment-@item.CommentId" class="post item span3">
                    <div class="well commentwell" id="FriendsListWell">
                        <div id="postContent">
                            <div class="PostPartialViewPhoto">
                                <a href="/Home/Profile/@item.User.UserId"><img class="PartialViewResponsive img-rounded pull-left" src="@Url.Content(item.User.ProfilePicture)" alt="Profile Picture" /></a>
                            </div>
                            <!--Should display username instead of item.userID-->
                            <div id="comm" style="margin-left:100px">
                                <div class="friendsListName">
                                    <h4>
                                        @Html.ActionLink(item.User.Name, "Profile", "Home", new { id = item.User.UserId }, null)
                                        <small class="pull-right">@Html.DisplayFor(modelItem => item.DateInserted)</small>
                                    </h4>

                                </div>
                                <div class="ellipsis-text preReset">
                                    <pre class="preReset">@item.Body</pre>
                                    <span class="more dontmove fakeLink">See more</span>
                                    <span class="less dontmove fakeLink">See less</span>
                                </div>
                                <span id="reactionCommentButtons">
                                    @if (item.User.UserId == User.Identity.GetUserId())
                                    {
                                        <button type="button" class="btn btn-danger deletePostButton deleteComment">Delete Comment</button>
                                        <input type="hidden" name="commentId" value="@item.CommentId" />
                                    }
                                </span>

                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

}