ConnectIn-master/ConnectInSolution/ConnectIn/Models/Entity/Notification.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ConnectIn.Models.Entity
{
    public class Notification
    {
        #region Columns
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int NotificationId { get; set; }
        public string FriendUserId { get; set; }
        public string UserId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime Date { get; set; }
        #endregion

        #region ForeignKeys
        public User User { get; set; }
        #endregion

        public Notification()
        {
            Date = DateTime.Now;
        }
    }
}

ConnectIn-master/ConnectInSolution/ConnectIn/Models/ViewModels/BirthdayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConnectIn.Models.ViewModels
{
    public class BirthdayViewModel
    {
        
        public UserViewModel User { get; set; }
    }
}

ConnectIn-master/ConnectInSolution/ConnectIn/Controllers/FriendController.cs
using System;
using System.Web.Mvc;
using ConnectIn.DAL;
using ConnectIn.Models.Entity;
using ConnectIn.Services;
using Microsoft.Ajax.Utilities;

namespace ConnectIn.Controllers
{
    public class FriendController : Controller
    {
        private readonly ApplicationDbContext DbContext = new ApplicationDbContext();
        
        [HttpPost, Authorize]
        public ActionResult Add(FormCollection collection)
        {
            string userId = collection["userId"];
            string friendId = collection["friendId"];

            if (userId.IsNullOrWhiteSpace() || friendId.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            var userService = new UserService(DbContext);

            var friendship = userService.GetFriendShip(userId, friendId);
            // If they are already friends, then it should not be possible to add him again
            if (friendship != null) return View("Error");
            var notification = new Notification()
            {
                UserId = userId,
                FriendUserId = friendId,
                GroupId = -1,
                Date = DateTime.Now
            };

            // Else add the friend
            DbContext.Notifications.Add(notification);
            DbContext.SaveChanges();

            return new EmptyResult();
        }

        [HttpPost, Authorize]
        public ActionResult Remove(FormCollection collection)
        {
            string userId = collection["userId"];
            string friendId = collection["friendId"];

            if (userId.IsNullOrWhiteSpace() || friendId.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            var userService = new UserService(DbContext);

            var friendShip = userService.GetFriendShip(userId, friendId);
            // If there is not friendship to remove, return a error
            if (friendShip == null) return View("Error");
            DbContext.Friends.Remove(friendShip);
            DbContext.SaveChanges();

            // If friend is removed from the profile, refresh the page
            var url = ControllerContext.HttpContext.Request.UrlReferrer;
            if (url != null && url.AbsolutePath.Contains("Profile"))
            {
                return RedirectToAction("Profile", "Home", new { id = friendId });
            }

            // Else asynchronously remove the friend
            return new EmptyResult();
        }

        [HttpPost, Authorize]
        public ActionResult AcceptFriendRequest(FormCollection collection)
        {
            string id = collection["notificationId"];
            if (id.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            var notificationService = new NotificationService(DbContext);

            int notificationId = Int32.Parse(id);
            var notification = notificationService.GetNotificationById(notificationId);
            // if the notification doesn't exist, return a error
            if (notification == null) return View("Error");

            var friends = new Friend
            {
                UserId = notification.UserId,
                FriendUserId = notification.FriendUserId
            };

            // Accept the friend and remove the notification
            DbContext.Notifications.Remove(notification);
            DbContext.Friends.Add(friends);
            DbContext.SaveChanges();
            
            return new EmptyResult();
        }

        [HttpPost, Authorize]
        public ActionResult DeclineFriendRequest(FormCollection collection)
        {
            string id = collection["notificationId"];
            if (id.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            var notificationService = new NotificationService(DbContext);

            int notificationId = Int32.Parse(id);
            var notification = notificationService.GetNotificationById(notificationId);
            // if the notification doesn't exist, return a error
            if (notification == null) return View("Error");
            
            // Reject the friend and remove the notification
            DbContext.Notifications.Remove(notification);
            DbContext.SaveChanges();

            return new EmptyResult();
        }

        [HttpPost, Authorize]
        public ActionResult HideGroupNotification(FormCollection collection)
        {
            string id = collection["groupNotificationId"];

            if (id.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            var notificationService = new NotificationService(DbContext);

            int notificationId = Int32.Parse(id);
            var notification = notificationService.GetNotificationById(notificationId);
            // if the notification doesn't exist, return a error
            if (notification == null) return View("Error");
            
            // Remove the group notification
            DbContext.Notifications.Remove(notification);
            DbContext.SaveChanges();

            return new EmptyResult();
        }
    }
}

ConnectIn-master/ConnectInSolution/ConnectIn/Controllers/NewsFeedController.cs
using System.Web.Mvc;
using ConnectIn.DAL;
using ConnectIn.Services;
using Microsoft.AspNet.Identity;

namespace ConnectIn.Controllers
{
    public class NewsFeedController : Controller
    {
        private readonly ApplicationDbContext DbContext = new ApplicationDbContext();

        [Authorize]
        [HttpGet]
        public ActionResult Everyone()
        {
            var userService = new UserService(DbContext);
            var posts = userService.GetEveryNewsFeedPostsForUser(User.Identity.GetUserId());

            return Json(posts, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public ActionResult BestFriends()
        {
            var userService = new UserService(DbContext);
            var posts = userService.GetBestFriendsPostsForUser(User.Identity.GetUserId());

            return Json(posts, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Family()
        {
            var userService = new UserService(DbContext);
            var posts = userService.GetFamilyPostsForUser(User.Identity.GetUserId());

            return Json(posts, JsonRequestBehavior.AllowGet);
        }
    }
}

ConnectIn-master/ConnectInSolution/ConnectIn/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using ConnectIn.DAL;
using ConnectIn.Models.Entity;
using ConnectIn.Models.ViewModels;
using ConnectIn.Services;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using ConnectIn.Utilities;
using System.Globalization;

namespace ConnectIn.Controllers
{
    public class PhotoController : Controller
    {
        private readonly ApplicationDbContext DbContext = new ApplicationDbContext();

        [HttpGet, Authorize]
        public ActionResult Images(string userId)
        {
            if (userId.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            var userService = new UserService(DbContext);
            var profilePhotos = userService.GetAllProfilePhotosFromUser(userId);
            var coverPhotos = userService.GetAllCoverPhotosFromUser(userId);

            // Filling the view model
            var model = new PhotoAlbumViewModel
            {
                ProfilePhotos = new List<PhotoViewModel>(),
                CoverPhotos = new List<PhotoViewModel>(),
                UserId = userId
            };

            foreach (var item in profilePhotos)
            {
                model.ProfilePhotos.Add(new PhotoViewModel()
                {
                    PhotoPath = item.PhotoPath,
                    PhotoId = item.PhotoId
                });
            }

            foreach (var item in coverPhotos)
            {
                model.CoverPhotos.Add(new PhotoViewModel()
                {
                    PhotoPath = item.PhotoPath,
                    PhotoId = item.PhotoId
                });
            }

            return View(model);
        }

        [HttpGet, Authorize]
        public ActionResult UploadProfilePhoto()
        {
            return View();
        }

        [HttpPost, Authorize]
        public ActionResult UploadProfilePhoto(FormCollection collection)
        {            
            // Getting file from input and converting it into byte array
            HttpPostedFileBase file = Request.Files["Image"];
            Int32 length = file.ContentLength;
            byte[] tempImage = new byte[length];
            file.InputStream.Read(tempImage, 0, length);

            // Creating the model for the new photo
            var photo = new Photo()
            {
                ContentType = file.ContentType,
                PhotoBytes = tempImage,
                UserId = User.Identity.GetUserId(),
                Date = DateTime.Now,
                IsProfilePhoto = false,
                IsCoverPhoto = false,
                IsCurrentCoverPhoto = false,
                IsCurrentProfilePhoto = false
            };

            // Saving it into the database
            DbContext.Photos.Add(photo);
            DbContext.SaveChanges();

            // Getting the new photoId that the database assigns to the photo for the photo path
            photo.PhotoPath = "/Photo/ShowPhoto?photoId=" + photo.PhotoId;
            DbContext.SaveChanges();

            return RedirectToAction("CropProfilePhoto", new { photoId = photo.PhotoId });
        }

        [HttpGet, Authorize]
        public ActionResult UploadCoverPhoto()
        {
            return View();
        }

        [HttpPost, Authorize]
        public ActionResult UploadCoverPhoto(FormCollection collection)
        {
            // Getting file from input and converting it into byte array
            HttpPostedFileBase file = Request.Files["Image"];
            Int32 length = file.ContentLength;
            byte[] tempImage = new byte[length];
            file.InputStream.Read(tempImage, 0, length);

            // Creating the model for the new photo
            var photo = new Photo()
            {
                ContentType = file.ContentType,
                PhotoBytes = tempImage,
                UserId = User.Identity.GetUserId(),
                Date = DateTime.Now,
                IsProfilePhoto = false,
                IsCoverPhoto = false,
                IsCurrentCoverPhoto = false,
                IsCurrentProfilePhoto = false
            };

            // Saving it into the database
            DbContext.Photos.Add(photo);
            DbContext.SaveChanges();

            // Getting the new photoId that the database assigns to the photo for the photo path
            photo.PhotoPath = "/Photo/ShowPhoto?photoId=" + photo.PhotoId;
            DbContext.SaveChanges();

            return RedirectToAction("CropCoverPhoto", new { photoId = photo.PhotoId });
        }

        [HttpPost, Authorize]
        public ActionResult DeletePhoto(int? photoId)
        {
            if (!photoId.HasValue)
            {
                return View("Error");
            }

            // Removing the photo that has photoId
            var photoService = new PhotoService(DbContext);
            DbContext.Photos.Remove(photoService.GetPhotoById(photoId.Value));
            DbContext.SaveChanges();

            return new EmptyResult();
        }

        [HttpGet, Authorize]
        public ActionResult ShowPhoto(int? photoId)
        {
            if (!photoId.HasValue)
            {
                return View("Error");
            }

            // Converting the byte array to an instance of ImageResult that can be represented as an image
            var photoService = new PhotoService(DbContext);
            Photo image = photoService.GetPhotoById(photoId.Value);
            ImageResult result = new ImageResult(image.PhotoBytes, image.ContentType);

            return result;
        }

        [HttpPost, Authorize]
        public ActionResult PickProfilePicture(FormCollection collection)
        {            
            string id = collection["photoId"];
            if (id.IsNullOrWhiteSpace())
            {
                return View("Error");
            }
            int photoId = Int32.Parse(id);
            
            // Switching profile pictures
            var userService = new UserService(DbContext);
            var oldPhoto = userService.GetProfilePicture(User.Identity.GetUserId());
            if(oldPhoto != null)
            {
                oldPhoto.IsCurrentProfilePhoto = false;
            }

            var photoService = new PhotoService(DbContext);
            photoService.GetPhotoById(photoId).IsCurrentProfilePhoto = true;
            DbContext.SaveChanges();

            return RedirectToAction("Profile", "Home", new { id = User.Identity.GetUserId() });
        }

        [HttpPost, Authorize]
        public ActionResult PickCoverPhoto(FormCollection collection)
        {            
            string id = collection["photoId"];
            if (id.IsNullOrWhiteSpace())
            {
                return View("Error");
            }
            int photoId = Int32.Parse(id);

            // Switching cover photos
            var userService = new UserService(DbContext);
            var photoService = new PhotoService(DbContext);

            var oldPhotoId = userService.GetCoverPhoto(User.Identity.GetUserId());
            var oldPhoto = photoService.GetPhotoById(oldPhotoId);
            if (oldPhoto != null)
            {
                oldPhoto.IsCurrentCoverPhoto = false;
            }
            photoService.GetPhotoById(photoId).IsCurrentCoverPhoto = true;
            DbContext.SaveChanges();

            return RedirectToAction("Profile", "Home", new { id = User.Identity.GetUserId() });
        }

        [HttpGet, Authorize]
        public ActionResult CropProfilePhoto(int? photoId)
        {
            if (!photoId.HasValue)
            {
                return View("Error");
            }

            // Get the photo and fill in the view model
            var photoService = new PhotoService(DbContext);
            var photo = photoService.GetPhotoById(photoId.Value);
            var model = new PhotoViewModel()
            {
                PhotoId = photo.PhotoId,
                PhotoPath = photo.PhotoPath
            };

            return View(model);
        }

        [HttpGet, Authorize]
        public ActionResult CropCoverPhoto(int? photoId)
        {
            if (!photoId.HasValue)
            {
                return View("Error");
            }

            // Get the photo and fill in the view model
            var photoService = new PhotoService(DbContext);
            var photo = photoService.GetPhotoById(photoId.Value);
            var model = new PhotoViewModel()
            {
                PhotoId = photo.PhotoId,
                PhotoPath = photo.PhotoPath
            };

            return View(model);
        }

        [HttpPost, Authorize]
        public virtual ActionResult CropImage(FormCollection collection)
        {
            string location = collection["location"];
            string sphotoId = collection["photoId"];
            string scropPointX = collection["cropPointX"];
            string scropPointY = collection["cropPointY"];
            string simageCropWidth = collection["imageCropWidth"];
            string simageCropHeight = collection["imageCropHeight"];
            if (location.IsNullOrWhiteSpace() || sphotoId.IsNullOrWhiteSpace() || scropPointX.IsNullOrWhiteSpace()
                || scropPointY.IsNullOrWhiteSpace() || simageCropWidth.IsNullOrWhiteSpace() || simageCropHeight.IsNullOrWhiteSpace())
            {
                return View("Error");
            }

            // Converting crop parameters to integers(sometimes they are double so we need to convert to double first)
            int cropPointX = Convert.ToInt32(double.Parse(scropPointX, CultureInfo.InvariantCulture));
            int cropPointY = Convert.ToInt32(double.Parse(scropPointY, CultureInfo.InvariantCulture));
            int imageCropWidth = Convert.ToInt32(double.Parse(simageCropWidth, CultureInfo.InvariantCulture));

ConnectIn-master/ConnectInSolution/ConnectIn/Views/Home/About.cshtml
@{
    ViewBag.Title = "Home Page";
}

<html>
<body>
<div id="disablingScroll">
    <div id="backgroundindex" class="carousel slide">
        <div class="carousel-inner">
            <div class="active item twoo"></div>
            <div class="item two"></div>
            <div class="item three"></div>
        </div>
    </div>

    <div class="jumbotron" id="headliner" style="text-align: center;">
        <h1>People behind Connect<span style="color: rgb(0, 190, 190)">In</span></h1>
    </div>

    <div class="row aboutRow">
        <div class="thumbnail right-caption span4">
            <img class="photosabout" id="darri" src="~/Content/images/darrivol2.jpg" alt="Darri">
            <div class="caption">
                <h2>CEO</h2>
                <h4>The person in charge of a company who has no other qualifications but thinks he or she does. </h4>
                <p>Born in Iceland, Darri soon rose to power as the CEO of the most sucessful business in Iceland's history.</p>
            </div>
        </div>
    </div>
    <br/>
    <div class="row aboutRow">
        <div class="thumbnail right-caption span4">
            <img class="photosabout" id="dabbi" src="~/Content/images/Dabbi.jpg" alt="David">
            <div class="caption">
                <h2>Project Manager</h2>
                <h4>Gets all the credit</h4>
                <p>As Darri's best friend, David soon applied for work which he of course got and is a project manager of search team.</p>
            </div>
        </div>
    </div>
    <br/>
    <div class="row aboutRow">
        <div class="thumbnail right-caption span4">
            <img class="photosabout" src="~/Content/images/thor2.jpg" alt="Thor">
            <div class="caption">
                <h2>CTO</h2>
                <h4>Technical founder who really can't manage anyone</h4>
                <p>Recently graduated from University of Reykjavik applied for the position CTO and by showing of his foosball skills soon got hired. </p>
            </div>
        </div>
    </div>
    <br/>
    <div class="row aboutRow">
        <div class="thumbnail right-caption span4">
            <img class="photosabout" src="~/Content/images/logi2.jpg" alt="Logi">
            <div class="caption">
                <h2>Graphic designer</h2>
                <h4>Takes the credit</h4>
                <p>Got recruited after having gotten a reputation for his mad paint skills.</p>
            </div>
        </div>
    </div>
    <br/>
    <div class="row aboutRow">
        <div class="thumbnail right-caption span4">
            <img class="photosabout" class="span2" src="~/Content/images/janitor.jpg" alt="Janitor">
            <div class="caption">
                <h2>Janitor</h2>
                <h4>Specifies in cleaning our code up</h4>
                <p>Problably the most important person in the company. Works day and night and never gets paid. </p>
            </div>
        </div>
    </div>



</div>
</body>
</html>

ConnectIn-master/ConnectInSolution/ConnectIn/Views/Home/Birthdays.cshtml
@model IEnumerable<ConnectIn.Models.ViewModels.BirthdayViewModel>

@{
    ViewBag.Title = "Birthdays";
}

@if (Request.IsAuthenticated)
{

    <div class="container">
        <h2>Birthdays</h2>
        <h3>Today is @DateTime.Today.ToString("dddd, MMMMM d", System.Globalization.CultureInfo.CreateSpecificCulture("en-US"))@string.Format("{1} {0:yyyy}", DateTime.Now, (DateTime.Now.Day%10 == 1 && DateTime.Now.Day != 11) ? "st"
                                                                                                                  : "th") </h3>
        <div id="posts" class="row">
                @foreach (var item in Model)
{
    <div class="post item span3" style="position:relative">
        <div class="well" id="FriendsListWell">
            <div class="friendsListPhoto">
                <a href="/Home/Profile/@item.User.UserId"><img class="img-responsive img-rounded smallPhoto" src="@Url.Content(item.User.ProfilePicture)" alt="Profile Picture" /></a>
            </div>
            <div class="friendsListAbout">
                <div class="friendsListName">
                    <h2 class="friendsListName">
                        @Html.ActionLink(item.User.Name, "Profile", new {id = item.User.UserId})
                    </h2>
                </div>
                <span>
                        @item.User.Birthday.Date.ToString("dd/MM/yyyy")
                </span>
            </div>
        </div>
        <div id="birthdayMarginAgeAbsolute">
            <span id="huge"> @String.Format("{0}", DateTime.Today.Year - item.User.Birthday.Year) years old</span>
        </div>
    </div>
}
            </div>
        </div>
    
    
}
else
{
<h1 id="loginSignUpMessage">
    Please log in or sign up to access your News Feed.
</h1>
}

ConnectIn-master/ConnectInSolution/ConnectIn/Views/Home/Profile.cshtml
@using ConnectIn.DAL
@using ConnectIn.Services
@using Microsoft.AspNet.Identity
@model ConnectIn.Models.ViewModels.ProfileViewModel

@{
    ViewBag.Title = "NewsFeed";
}
@if (Request.IsAuthenticated)
{

    <div class="coverPhotoProfile" style="background-image: url(@Url.Content(Model.User.CoverPhoto));">
        <div class="coverPhotoGradient" >
            <div class="pull-right">
                @{
    var db = new ApplicationDbContext();
    var userService = new UserService(db);
                    var notificationService = new NotificationService(db);
    var friendShip = userService.GetFriendShip(User.Identity.GetUserId(), Model.User.UserId);
                }
                <div id="addFriendButton">
                    @if (Model.User.UserId != User.Identity.GetUserId())
                    {
                        var listOfFriends = userService.GetFriendsFromUser(User.Identity.GetUserId());
                        var notification = notificationService.GetIfFriendRequestIsPending(User.Identity.GetUserId(), Model.User.UserId);
                        if (notification != null)
                        {
                            <button type="button" class="btn">Pending</button>
                        }
                        else if (listOfFriends.Contains(@Model.User.UserId))
                        {
                            using (Html.BeginForm("Remove", "Friend"))
                            {

                                <input type="hidden" name="userId" value="@User.Identity.GetUserId()" />
                                <input type="hidden" name="friendId" value="@Model.User.UserId" />
                                <button type="submit" class="btn btn-danger dangerFix">
                                    <i class=" glyphicon glyphicon-minus"></i>&nbsp;Remove friend
                                </button>
                            }
                        }
                        else
                        {
                            <div id="addFriend-@Model.User.UserId">
                                <input type="hidden" name="userId" value="@User.Identity.GetUserId()" />
                                <input type="hidden" name="friendId" value="@Model.User.UserId" />
                                <button type="submit" class="btn btn-success addFriend"><i class="glyphicon glyphicon-plus"></i>&nbsp;Add friend</button>
                            </div>
                        }
                    }
                </div>
                <div class="profileStars">

                    @if (Model.User.UserId != User.Identity.GetUserId() && friendShip != null)
                    {
                        <button id="bestFriend-@Model.User.UserId" style="color: white;" type="submit" class="btnNew btn-default-clicked bestFriend"><img id="bffamimg" src="@Url.Content(@Model.User.BfStar)" alt="Star" /><span class="glyphicon bffam starColor">Best Friend</span></button>
                        <input type="hidden" name="friendId" value="@Model.User.UserId" />

                        <button id="family-@Model.User.UserId" style="color: white;" type="submit" class="btnNew btn-default-clicked family"><img id="bffamimg" src="@Url.Content(@Model.User.FStar)" alt="Star" /><span class="glyphicon bffam starColor">Family</span></button>
                        <input type="hidden" name="friendId" value="@Model.User.UserId" />
                    }
                </div>
            </div>
            <div id="userProfilePicture">
                <img class="img-responsiveProfilePic img-thumbnail" src="@Url.Content(Model.User.ProfilePicture)" alt="Profile Picture" />
            </div>
            <div id="userNameOnProfile">

                <h1 id="userNameH1">
                    @string.Format("{0}", Model.User.Name)
                </h1>

                @{
                    var user = userService.GetUserById(Model.User.UserId);
                    friendShip = userService.GetFriendShip(user.Id, User.Identity.GetUserId());
                    if (user.Id == User.Identity.GetUserId() || user.Privacy == 0 || (user.Privacy == 1 && friendShip != null) || (user.Privacy == 2 && userService.FriendConsidersUserClose(user.Id, User.Identity.GetUserId())))
                    {
                        <div id="PhotoButton">
                            @using (Html.BeginForm("Images", "Photo", FormMethod.Get))
                            {
                                <input type="hidden" name="userId" value="@Model.User.UserId"/>
                                <button type="submit" class="btn fa fa-camera btn-primary"></button>
                            }
                        </div>
                    }
                }

            </div>
        </div>
    </div>
    <div id="profileborder"></div>
    
    <div class="well" id="aboutUser">
                    <table class="tableFriends">
                        <tbody>
                        <tr>
                            <td class="glyphicon glyphicon-user tableItem">
                                Gender
                            </td>
                            <td class="glyphicon profileGender tableItemInfo">
                                <span>@string.Format("{0}", Model.User.Gender)</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="glyphicon glyphicon-gift tableItem">
                                Birthday
                            </td>
                            <td class="glyphicon profileBirthday tableItemInfo">
                                <span>@string.Format("{0}.{1}.{2}", Model.User.Birthday.Day, Model.User.Birthday.Month, Model.User.Birthday.Year)</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="glyphicon glyphicon-briefcase tableItem">
                                Work
                            </td>
                            <td class="glyphicon workFriendsList tableItemInfo">
                                <span>@string.Format("{0}", Model.User.Work)</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="glyphicon glyphicon-book tableItem">
                                School
                            </td>
                            <td class="glyphicon schoolFriendsList tableItemInfo">
                                <span>@string.Format("{0}", Model.User.School)</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="glyphicon glyphicon-home tableItem">
                                Address
                            </td>
                            <td class="glyphicon workFriendsList tableItemInfo">
                                <span>@string.Format("{0}", Model.User.Address)</span>
                            </td>
                        </tr>
                        @if (Model.User.UserId == User.Identity.GetUserId())
                        {
                            <tr>
                                <td id="hidebutton" class="glyphicon  tableItem">
                                    <a id="Editpencil" href="@Url.Action("Edit", "Account")" class="glyphicon-pencil">
                                        Edit
                                    </a>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
    
    
    
    {
        if (user.Id == User.Identity.GetUserId() || user.Privacy == 0 || (user.Privacy == 1 && friendShip != null) || (user.Privacy == 2 && userService.FriendConsidersUserClose(user.Id, User.Identity.GetUserId())))
        {
            <div id="ProfilePostWell">
                @{
                    Html.RenderPartial("PostsPartial", Model.NewsFeed);
                }
            </div>
        }
    }
}
else
{
    <h1 id="loginSignUpMessage">
        Please log in or sign up to access Profile.
    </h1>
}