MoooLien/MoooLien/Models/Administrator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoooLien.Models
{
    public class Administrator
    {
        public class Course
        {
            public int ID { get; set; }
            public string name { get; set; }
            public string description { get; set; }
        }

    }
}

MoooLien/MoooLien/Models/Entities/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoooLien.Models.Entities
{
    public class Course
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}

MoooLien/MoooLien/Models/ViewModel/CourseViewModel.cs
using MoooLien.Models.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MoooLien.Models.ViewModel
{
    public class CourseViewModel
    {
        public List<Course> courses { get; set; }
        public Course course { get; set; }
    }

    public class CreateCourseViewModel
    {
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        [StringLength(100, ErrorMessage = "Enter a valid name for Course", MinimumLength = 2)]
        public string name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Description")]
        public string description { get; set; }
    }
    public class EditCourseViewModel
    {
        public string ID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        [StringLength(100, ErrorMessage = "Please enter valid course name", MinimumLength = 2)]
        public string name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Description")]
        public string description { get; set; }
    }
}

MoooLien/MoooLien/Models/ViewModel/UserViewModel.cs
using MoooLien.Models.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MoooLien.Models.ViewModel
{
    public class UserViewModel
    {
        public List<ApplicationUser> users { get; set; }
        public ApplicationUser user { get; set; }
    }
}

MoooLien/MoooLien/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MoooLien.DAL;
using MoooLien.Models.Entities;

namespace MoooLien.Views.Account
{
    [Authorize(Roles = "Administrators")]
    public class AdministratorController : Controller
    {
        private DefaultConnection db = new DefaultConnection();

        // GET: Administrator
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Users()
        {
            return View();
        }

        public ActionResult Courses()
        {
            return View(db.Courses.ToList());
        }

        // GET: Administrator/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Administrator/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,name,description")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(course);
        }

        // GET: Administrator/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Administrator/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,name,description")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        // GET: Administrator/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Administrator/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MoooLien/MoooLien/Controllers/AdministratorsController.cs
using System.Web.Mvc;
using MoooLien.Models.ViewModel;
using MoooLien.Service;

namespace MoooLien.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class AdministratorsController : Controller
    {
        #region Service connection
        private UsersService uService = new UsersService(null);
        private CourseService cService = new CourseService(null);
        private UsersInCourseService uInCService = new UsersInCourseService(null);
        #endregion

        #region Index()
        //Index()
        public ActionResult Index()
        {

            return View();
        }
        #endregion

        #region Create()
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }
        #endregion

        #region List()
        public ActionResult List()
        {
            UserViewModel model = uService.getAllUsers();
            return View(model);
        }
        #endregion

        #region ManageUsers()
        public ActionResult ManageUsers()
        {
            UserViewModel model = uService.getAllUsers();
            return View(model);
        }
        #endregion

        #region ManageCourses()
        public ActionResult ManageCourses()
        {
            cService.getAllCourses();
            return View(cService.getAllCourses());
        }
        #endregion

        #region Enrole(int id)
        public ActionResult Enrole(int id)
        {
            ViewBag.courseID = id;
            
            return View(uService.getUsersByCourseID(id));
        }
        #endregion

        #region moveToStudent(string userID, int courseID)
        public ActionResult moveToStudent(string userID, int courseID)
        {

            if (uInCService.userExists(userID, courseID, 2))
            {
                uInCService.removeLink(userID, courseID);
            }
            uInCService.createLink(userID, courseID, 1);
            return RedirectToAction("Enrole", "Administrators", new { id = courseID });
        }
        #endregion

        #region moveToTeacher(string userID, int courseID)
        public ActionResult moveToTeacher(string userID, int courseID)
        {
            if (uInCService.userExists(userID, courseID, 1))
            {
                uInCService.removeLink(userID, courseID);
            }
            uInCService.createLink(userID, courseID, 2);
            return RedirectToAction("Enrole", "Administrators", new { id = courseID });
        }
        #endregion

        #region removeFromCourse(string userID, int courseID)
        public ActionResult removeFromCourse(string userID, int courseID)
        {
            uInCService.removeLink(userID, courseID);
            return RedirectToAction("Enrole", "Administrators", new { id = courseID });
        }
        #endregion

    }
}

MoooLien/MoooLien/Controllers/CoursesController.cs
using System.Web.Mvc;
using MoooLien.Models.Entities;
using MoooLien.Service;
using MoooLien.Models.ViewModel;
using Microsoft.AspNet.Identity;

namespace MoooLien.Controllers
{
    public class CoursesController : Controller
    {
        #region Server conections
        private CourseService cService = new CourseService(null);
        #endregion

        #region Index()
        // GET: Courses
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            CourseViewModel cView = cService.getAllCourses();
            return View(cView);
        }
        #endregion

        #region UserIndex()
        public ActionResult UserIndex()
        {
            var userid = User.Identity.GetUserId();
            return View(cService.getCourseByUserID(userid));
        }
        #endregion

        #region Create()
        // GET: Courses/Details/5
        public ActionResult Create()
        {
            return View();
        }
        #endregion

        #region Create(CreateCourseViewModel newCourse)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCourseViewModel newCourse)
        {
            if(cService.add(newCourse))
            {
                return RedirectToAction("ManageCourses", "Administrators");
            }
            else
            {
                ModelState.AddModelError("", "Couldn't add new course, please try again");
                return (RedirectToAction("Create"));
            }
        }
        #endregion

        #region Delete(int id)
        public ActionResult Delete(int id)
        {
            if(cService.deleteCourse(id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Deletetion of user failed");
                return RedirectToAction("Index");
            }
        }
        #endregion

        # region Edit(int id)
        public ActionResult Edit(int id)
        {
            return View();
        }
        #endregion
    }
}

MoooLien/MoooLien/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using MoooLien.Models;
using MoooLien.Models.ViewModel;
using MoooLien.Service;
using System.Threading.Tasks;
using System.Web.Mvc;
using System;
using System.Web;
using Microsoft.AspNet.Identity.Owin;

namespace MoooLien.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private UsersService uService = new UsersService(null);
        private ApplicationUserManager userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                userManager = value;
            }
        }

        // GET: Users
        public ActionResult Index()
        {
            UserViewModel model = uService.getAllUsers();
            return View(model);
        }

        public async Task<ActionResult> Remove(string id)
        {
            if (id != null)
            {
                ApplicationUser user = await UserManager.FindByIdAsync(id);
                if (uService.CanDeleteUser(user))
                {
                    var result = UserManager.Delete(user);
                    if (result.Succeeded)
                    {
                        TempData["message"] = user.UserName + " has be deleted from the system";
                    }
                    else
                    {
                        TempData["errorMessage"] = "An error occured while trying to delete " + user.UserName;
                    }
                }
                return RedirectToAction("index", "user");
            }
            return View("404");
        }

        public ActionResult Enrole()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Enrole(FormCollection wasIstDas)
        {
            /*uService.getUsersCoursesAndRole();*/

            return null;
        }

    }
    
}

MoooLien/MoooLien/Views/Administrator/Courses.cshtml
@model IEnumerable<MoooLien.Models.Entities.Course>

@{
    ViewBag.Title = "Manage Courses";
    Layout = "~/Views/Administrator/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

<p>
    <a href="~/Administrator/Create" class="btn btn-success">Create Course</a>
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td width="10%">
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

MoooLien/MoooLien/Views/Administrator/Create.cshtml
@model MoooLien.Models.Entities.Course

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Administrator/_Layout.cshtml";
}
<h2>Create Course</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, 10, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Courses")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MoooLien/MoooLien/Views/Administrator/Delete.cshtml
@model MoooLien.Models.Entities.Course

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Administrator/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Courses")
        </div>
    }
</div>

MoooLien/MoooLien/Views/Administrator/Edit.cshtml
@model MoooLien.Models.Entities.Course

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Administrator/_Layout.cshtml";
}
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, 10, 40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Courses")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MoooLien/MoooLien/Views/Administrator/Index.cshtml
@model IEnumerable<MoooLien.Models.Entities.Course>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Administrator/_Layout.cshtml";
}

<h2>Velkominn herra admin!</h2>

MoooLien/MoooLien/Views/Administrator/Users.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Manage Users";
    Layout = "~/Views/Administrator/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    <a href="~/Account/Register" class="btn btn-success">Create User</a>
</p>

<p>
  
</p>

<li>
    @Html.ActionLink(User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
</li>

MoooLien/MoooLien/Views/Administrator/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MoooLien", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                 
                     <li>@Html.ActionLink("Manage Courses", "Courses", "Administrator")</li>
                     <li>@Html.ActionLink("Manage Users", "Users", "Administrator")</li>
                 @*    <li>@Html.ActionLink("Test Auth", "TestAuth", "Home")</li>
                *@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; The A-Team</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>